SCAN_SESSIONS_COLLECTION = "scan_sessions"
SCAN_JOBS_COLLECTION = "scan_jobs"
FINDINGS_COLLECTION = "findings"
FIX_SUGGESTIONS_COLLECTION = "fix_suggestions"
VERIFICATION_RUNS_COLLECTION = "verification_runs"
AUDIT_EVENTS_COLLECTION = "audit_events"
REPORT_EXPORTS_COLLECTION = "report_exports"
LEARNING_ARCHIVE_RUNS_COLLECTION = "learning_archive_runs"
LEARNING_ARCHIVE_ITEMS_COLLECTION = "learning_archive_items"
LEARNING_ARCHIVE_CHUNKS_COLLECTION = "learning_archive_chunks"
EXTERNAL_KNOWLEDGE_SOURCES_COLLECTION = "external_knowledge_sources"
EXTERNAL_KNOWLEDGE_ITEMS_COLLECTION = "external_knowledge_items"
EXTERNAL_KNOWLEDGE_CHUNKS_COLLECTION = "external_knowledge_chunks"
BENCHMARK_SUITES_COLLECTION = "benchmark_suites"
BENCHMARK_CASES_COLLECTION = "benchmark_cases"
BENCHMARK_RUNS_COLLECTION = "benchmark_runs"
FEEDBACK_EVENTS_COLLECTION = "feedback_events"
NORMALIZATION_FAILURES_COLLECTION = "normalization_failures"
INGESTION_AUDIT_COLLECTION = "ingestion_audit"
RUNTIME_SETTINGS_COLLECTION = "runtime_settings"
BUILDER_WORKSPACES_COLLECTION = "builder_workspaces"
BUILDER_THREADS_COLLECTION = "builder_threads"
BUILDER_MESSAGES_COLLECTION = "builder_messages"

REQUIRED_COLLECTIONS = (
    SCAN_SESSIONS_COLLECTION,
    SCAN_JOBS_COLLECTION,
    FINDINGS_COLLECTION,
    FIX_SUGGESTIONS_COLLECTION,
    VERIFICATION_RUNS_COLLECTION,
    AUDIT_EVENTS_COLLECTION,
    REPORT_EXPORTS_COLLECTION,
    LEARNING_ARCHIVE_RUNS_COLLECTION,
    LEARNING_ARCHIVE_ITEMS_COLLECTION,
    LEARNING_ARCHIVE_CHUNKS_COLLECTION,
    EXTERNAL_KNOWLEDGE_SOURCES_COLLECTION,
    EXTERNAL_KNOWLEDGE_ITEMS_COLLECTION,
    EXTERNAL_KNOWLEDGE_CHUNKS_COLLECTION,
    BENCHMARK_SUITES_COLLECTION,
    BENCHMARK_CASES_COLLECTION,
    BENCHMARK_RUNS_COLLECTION,
    FEEDBACK_EVENTS_COLLECTION,
    NORMALIZATION_FAILURES_COLLECTION,
    INGESTION_AUDIT_COLLECTION,
    RUNTIME_SETTINGS_COLLECTION,
    BUILDER_WORKSPACES_COLLECTION,
    BUILDER_THREADS_COLLECTION,
    BUILDER_MESSAGES_COLLECTION,
)
